# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.terms_updated import TermsUpdated


class TestTermsUpdated(unittest.TestCase):
    """ TermsUpdated unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTermsUpdated(self):
        """
        Test TermsUpdated
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.terms_updated.TermsUpdated()
        pass


if __name__ == '__main__':
    unittest.main()
