# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.contacts_deleted import ContactsDeleted


class TestContactsDeleted(unittest.TestCase):
    """ ContactsDeleted unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactsDeleted(self):
        """
        Test ContactsDeleted
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.contacts_deleted.ContactsDeleted()
        pass


if __name__ == '__main__':
    unittest.main()
