# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.student import Student


class TestStudent(unittest.TestCase):
    """ Student unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudent(self):
        """
        Test Student
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.student.Student()
        pass


if __name__ == '__main__':
    unittest.main()
