# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.student_contact_response import StudentContactResponse


class TestStudentContactResponse(unittest.TestCase):
    """ StudentContactResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudentContactResponse(self):
        """
        Test StudentContactResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.student_contact_response.StudentContactResponse()
        pass


if __name__ == '__main__':
    unittest.main()
