# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.course_response import CourseResponse


class TestCourseResponse(unittest.TestCase):
    """ CourseResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCourseResponse(self):
        """
        Test CourseResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.course_response.CourseResponse()
        pass


if __name__ == '__main__':
    unittest.main()
