# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.student_response import StudentResponse


class TestStudentResponse(unittest.TestCase):
    """ StudentResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudentResponse(self):
        """
        Test StudentResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.student_response.StudentResponse()
        pass


if __name__ == '__main__':
    unittest.main()
