# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.district_response import DistrictResponse


class TestDistrictResponse(unittest.TestCase):
    """ DistrictResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistrictResponse(self):
        """
        Test DistrictResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.district_response.DistrictResponse()
        pass


if __name__ == '__main__':
    unittest.main()
