# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import clever
from clever.rest import ApiException
from clever.models.sections_deleted import SectionsDeleted


class TestSectionsDeleted(unittest.TestCase):
    """ SectionsDeleted unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSectionsDeleted(self):
        """
        Test SectionsDeleted
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = clever.models.sections_deleted.SectionsDeleted()
        pass


if __name__ == '__main__':
    unittest.main()
