# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.bad_request import BadRequest
from .models.credentials import Credentials
from .models.district import District
from .models.district_admin import DistrictAdmin
from .models.district_admin_response import DistrictAdminResponse
from .models.district_admins_response import DistrictAdminsResponse
from .models.district_object import DistrictObject
from .models.district_response import DistrictResponse
from .models.district_status import DistrictStatus
from .models.district_status_response import DistrictStatusResponse
from .models.district_status_responses import DistrictStatusResponses
from .models.districts_response import DistrictsResponse
from .models.event import Event
from .models.event_response import EventResponse
from .models.events_response import EventsResponse
from .models.grade_levels_response import GradeLevelsResponse
from .models.internal_error import InternalError
from .models.location import Location
from .models.name import Name
from .models.not_found import NotFound
from .models.principal import Principal
from .models.school import School
from .models.school_admin import SchoolAdmin
from .models.school_admin_object import SchoolAdminObject
from .models.school_admin_response import SchoolAdminResponse
from .models.school_admins_response import SchoolAdminsResponse
from .models.school_object import SchoolObject
from .models.school_response import SchoolResponse
from .models.schools_response import SchoolsResponse
from .models.section import Section
from .models.section_object import SectionObject
from .models.section_response import SectionResponse
from .models.sections_response import SectionsResponse
from .models.student import Student
from .models.student_contact import StudentContact
from .models.student_contact_object import StudentContactObject
from .models.student_contact_response import StudentContactResponse
from .models.student_contacts_for_student_response import StudentContactsForStudentResponse
from .models.student_contacts_response import StudentContactsResponse
from .models.student_object import StudentObject
from .models.student_response import StudentResponse
from .models.students_response import StudentsResponse
from .models.teacher import Teacher
from .models.teacher_object import TeacherObject
from .models.teacher_response import TeacherResponse
from .models.teachers_response import TeachersResponse
from .models.term import Term
from .models.districts_created import DistrictsCreated
from .models.districts_deleted import DistrictsDeleted
from .models.districts_updated import DistrictsUpdated
from .models.schooladmins_created import SchooladminsCreated
from .models.schooladmins_deleted import SchooladminsDeleted
from .models.schooladmins_updated import SchooladminsUpdated
from .models.schools_created import SchoolsCreated
from .models.schools_deleted import SchoolsDeleted
from .models.schools_updated import SchoolsUpdated
from .models.sections_created import SectionsCreated
from .models.sections_deleted import SectionsDeleted
from .models.sections_updated import SectionsUpdated
from .models.studentcontacts_created import StudentcontactsCreated
from .models.studentcontacts_deleted import StudentcontactsDeleted
from .models.studentcontacts_updated import StudentcontactsUpdated
from .models.students_created import StudentsCreated
from .models.students_deleted import StudentsDeleted
from .models.students_updated import StudentsUpdated
from .models.teachers_created import TeachersCreated
from .models.teachers_deleted import TeachersDeleted
from .models.teachers_updated import TeachersUpdated

# import apis into sdk package
from .apis.data_api import DataApi
from .apis.events_api import EventsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
