# Copy autogenerated files into clever directory and rename
cp -R swagger_client/. clever || true
rm -rf swagger_client|| true

# Rename references of swagger client to Clever
git grep -l 'swagger_client' -- './*' ':(exclude)override/override.sh' | xargs sed -i "" 's/swagger_client/clever/g'
git grep -l 'swagger-client' -- './*' ':(exclude)override/override.sh' | xargs sed -i "" 's/swagger-client/clever-python/g'
