# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DistrictStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'id': 'str',
        'last_sync': 'str',
        'launch_date': 'str',
        'pause_end': 'str',
        'pause_start': 'str',
        'sis_type': 'str',
        'state': 'str'
    }

    attribute_map = {
        'error': 'error',
        'id': 'id',
        'last_sync': 'last_sync',
        'launch_date': 'launch_date',
        'pause_end': 'pause_end',
        'pause_start': 'pause_start',
        'sis_type': 'sis_type',
        'state': 'state'
    }

    def __init__(self, error=None, id=None, last_sync=None, launch_date=None, pause_end=None, pause_start=None, sis_type=None, state=None):
        """
        DistrictStatus - a model defined in Swagger
        """

        self._error = None
        self._id = None
        self._last_sync = None
        self._launch_date = None
        self._pause_end = None
        self._pause_start = None
        self._sis_type = None
        self._state = None

        if error is not None:
          self.error = error
        if id is not None:
          self.id = id
        if last_sync is not None:
          self.last_sync = last_sync
        if launch_date is not None:
          self.launch_date = launch_date
        if pause_end is not None:
          self.pause_end = pause_end
        if pause_start is not None:
          self.pause_start = pause_start
        if sis_type is not None:
          self.sis_type = sis_type
        if state is not None:
          self.state = state

    @property
    def error(self):
        """
        Gets the error of this DistrictStatus.

        :return: The error of this DistrictStatus.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """
        Sets the error of this DistrictStatus.

        :param error: The error of this DistrictStatus.
        :type: str
        """

        self._error = error

    @property
    def id(self):
        """
        Gets the id of this DistrictStatus.

        :return: The id of this DistrictStatus.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this DistrictStatus.

        :param id: The id of this DistrictStatus.
        :type: str
        """

        self._id = id

    @property
    def last_sync(self):
        """
        Gets the last_sync of this DistrictStatus.

        :return: The last_sync of this DistrictStatus.
        :rtype: str
        """
        return self._last_sync

    @last_sync.setter
    def last_sync(self, last_sync):
        """
        Sets the last_sync of this DistrictStatus.

        :param last_sync: The last_sync of this DistrictStatus.
        :type: str
        """

        self._last_sync = last_sync

    @property
    def launch_date(self):
        """
        Gets the launch_date of this DistrictStatus.

        :return: The launch_date of this DistrictStatus.
        :rtype: str
        """
        return self._launch_date

    @launch_date.setter
    def launch_date(self, launch_date):
        """
        Sets the launch_date of this DistrictStatus.

        :param launch_date: The launch_date of this DistrictStatus.
        :type: str
        """

        self._launch_date = launch_date

    @property
    def pause_end(self):
        """
        Gets the pause_end of this DistrictStatus.

        :return: The pause_end of this DistrictStatus.
        :rtype: str
        """
        return self._pause_end

    @pause_end.setter
    def pause_end(self, pause_end):
        """
        Sets the pause_end of this DistrictStatus.

        :param pause_end: The pause_end of this DistrictStatus.
        :type: str
        """

        self._pause_end = pause_end

    @property
    def pause_start(self):
        """
        Gets the pause_start of this DistrictStatus.

        :return: The pause_start of this DistrictStatus.
        :rtype: str
        """
        return self._pause_start

    @pause_start.setter
    def pause_start(self, pause_start):
        """
        Sets the pause_start of this DistrictStatus.

        :param pause_start: The pause_start of this DistrictStatus.
        :type: str
        """

        self._pause_start = pause_start

    @property
    def sis_type(self):
        """
        Gets the sis_type of this DistrictStatus.

        :return: The sis_type of this DistrictStatus.
        :rtype: str
        """
        return self._sis_type

    @sis_type.setter
    def sis_type(self, sis_type):
        """
        Sets the sis_type of this DistrictStatus.

        :param sis_type: The sis_type of this DistrictStatus.
        :type: str
        """

        self._sis_type = sis_type

    @property
    def state(self):
        """
        Gets the state of this DistrictStatus.

        :return: The state of this DistrictStatus.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this DistrictStatus.

        :param state: The state of this DistrictStatus.
        :type: str
        """
        allowed_values = ["running", "pending", "error", "paused"]
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DistrictStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
