# coding: utf-8

"""
    Clever API

    The Clever API

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Location(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'city': 'str',
        'lat': 'str',
        'lon': 'str',
        'state': 'str',
        'zip': 'str'
    }

    attribute_map = {
        'address': 'address',
        'city': 'city',
        'lat': 'lat',
        'lon': 'lon',
        'state': 'state',
        'zip': 'zip'
    }

    def __init__(self, address=None, city=None, lat=None, lon=None, state=None, zip=None):
        """
        Location - a model defined in Swagger
        """

        self._address = None
        self._city = None
        self._lat = None
        self._lon = None
        self._state = None
        self._zip = None
        self.discriminator = None

        if address is not None:
          self.address = address
        if city is not None:
          self.city = city
        if lat is not None:
          self.lat = lat
        if lon is not None:
          self.lon = lon
        if state is not None:
          self.state = state
        if zip is not None:
          self.zip = zip

    @property
    def address(self):
        """
        Gets the address of this Location.

        :return: The address of this Location.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """
        Sets the address of this Location.

        :param address: The address of this Location.
        :type: str
        """

        self._address = address

    @property
    def city(self):
        """
        Gets the city of this Location.

        :return: The city of this Location.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this Location.

        :param city: The city of this Location.
        :type: str
        """

        self._city = city

    @property
    def lat(self):
        """
        Gets the lat of this Location.

        :return: The lat of this Location.
        :rtype: str
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """
        Sets the lat of this Location.

        :param lat: The lat of this Location.
        :type: str
        """

        self._lat = lat

    @property
    def lon(self):
        """
        Gets the lon of this Location.

        :return: The lon of this Location.
        :rtype: str
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """
        Sets the lon of this Location.

        :param lon: The lon of this Location.
        :type: str
        """

        self._lon = lon

    @property
    def state(self):
        """
        Gets the state of this Location.

        :return: The state of this Location.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this Location.

        :param state: The state of this Location.
        :type: str
        """

        self._state = state

    @property
    def zip(self):
        """
        Gets the zip of this Location.

        :return: The zip of this Location.
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """
        Sets the zip of this Location.

        :param zip: The zip of this Location.
        :type: str
        """

        self._zip = zip

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Location):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
